# Telegram Bot Configuration
bot.name=Dwyd
bot.token=
bot.username=Dwyd_bot

# Bot Settings
bot.admin.id=

# Bot behavior
bot.welcome.message=Привет!
bot.help.message=Делается так

# Server by sent
server.url=http://localhost:8080/api/marketCheck/v1/save
