# Bot message
bot.message.welcome=Привет!
bot.message.help=Делается так
bot.message.answer.yes=Товар добавлен
bot.message.answer.no=Товар не добавлен
bot.message.instruction=Отправьте ссылку на товар и артикль товара

# Bot button name
bot.button.help=Помощь
bot.button.add=Добавить товар

# Dwyd server urls
server.url.save=http://localhost:8080/api/marketCheck/v1/save
server.url.notification=http://localhost:8080/api/marketCheck/v1/notification