spring:
  application:
    name: Dwyd
  jpa:
    hibernate:
      ddl-auto: validate  # Liquibase управляет схемой
    show-sql: false
  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: dev
  main:
    banner-mode: off

# Настройки для задач
tasks:
  save:
    task-name: save
    check-after-save: false
  start:
    task-name: start
    time-delay: 5
  need-auth: false